name: macos_ui_example
version: 1.0.0+1
publish_to: none
description: Demonstrates how to use the macos_ui package
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.5
  macos_ui:
    path: /Users/ericm/sunny/local_plugins/macos_ui
dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/sf_symbols/
