name: macos_ui_example
version: 1.0.0+1
publish_to: none
description: Demonstrates how to use the macos_ui package
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  macos_ui: 
    git: 
      url: git@github.com:SunnyApp/macos_ui.git
      ref: trippi_app
dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/sf_symbols/
